ALTER TABLE public.contact_attribution
  ADD COLUMN IF NOT EXISTS utm_id text,
  ADD COLUMN IF NOT EXISTS utm_adgroup text,
  ADD COLUMN IF NOT EXISTS ad_campaign_name text,
  ADD COLUMN IF NOT EXISTS ad_group_name text,
  ADD COLUMN IF NOT EXISTS ad_name text,
  ADD COLUMN IF NOT EXISTS google_campaign_id text,
  ADD COLUMN IF NOT EXISTS google_adgroup_id text,
  ADD COLUMN IF NOT EXISTS google_creative_id text,
  ADD COLUMN IF NOT EXISTS google_keyword text,
  ADD COLUMN IF NOT EXISTS google_matchtype text,
  ADD COLUMN IF NOT EXISTS google_network text,
  ADD COLUMN IF NOT EXISTS google_device text,
  ADD COLUMN IF NOT EXISTS google_devicemodel text,
  ADD COLUMN IF NOT EXISTS google_placement text,
  ADD COLUMN IF NOT EXISTS google_adposition text,
  ADD COLUMN IF NOT EXISTS google_target_id text,
  ADD COLUMN IF NOT EXISTS google_loc_physical text,
  ADD COLUMN IF NOT EXISTS google_loc_interest text,
  ADD COLUMN IF NOT EXISTS google_feed_item_id text,
  ADD COLUMN IF NOT EXISTS meta_form_name text,
  ADD COLUMN IF NOT EXISTS meta_placement text,
  ADD COLUMN IF NOT EXISTS meta_site_source text,
  ADD COLUMN IF NOT EXISTS meta_lead_id text,
  ADD COLUMN IF NOT EXISTS meta_page_id text,
  ADD COLUMN IF NOT EXISTS meta_is_organic boolean,
  ADD COLUMN IF NOT EXISTS meta_created_time timestamptz,
  ADD COLUMN IF NOT EXISTS extra jsonb NOT NULL DEFAULT '{}'::jsonb;