-- Realtime for ai_agent_runs
ALTER TABLE public.ai_agent_runs REPLICA IDENTITY FULL;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'ai_agent_runs'
  ) THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE public.ai_agent_runs';
  END IF;
END $$;

-- Recompute next_run_at server-side from a stored cron expression.
-- Supports the presets generated by the Agents UI:
--   m h * * *           daily
--   m h * * 1-5         weekdays
--   m h * * 1           Mondays
--   m h,h * * 1-5       twice/day weekdays
CREATE OR REPLACE FUNCTION public.ai_recompute_next_run(p_agent_id uuid)
RETURNS timestamptz
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  rec record;
  parts text[];
  mins int[];
  hours int[];
  dows  text;
  candidate timestamptz;
  base timestamptz := now();
  best timestamptz := NULL;
  d int;
  h int;
  m int;
  dow_int int;
BEGIN
  SELECT id, schedule, is_active INTO rec FROM public.ai_agents WHERE id = p_agent_id;
  IF rec IS NULL OR NOT rec.is_active THEN
    UPDATE public.ai_agents SET next_run_at = NULL WHERE id = p_agent_id;
    RETURN NULL;
  END IF;

  parts := regexp_split_to_array(trim(rec.schedule), '\s+');
  IF array_length(parts, 1) <> 5 THEN
    RETURN NULL;
  END IF;

  -- minutes
  SELECT array_agg(x::int) INTO mins
  FROM unnest(string_to_array(parts[1], ',')) x WHERE x ~ '^\d+$';
  -- hours
  SELECT array_agg(x::int) INTO hours
  FROM unnest(string_to_array(parts[2], ',')) x WHERE x ~ '^\d+$';
  dows := parts[5];

  IF mins IS NULL OR hours IS NULL THEN
    RETURN NULL;
  END IF;

  FOR d IN 0..14 LOOP
    candidate := (base + make_interval(days => d));
    dow_int := EXTRACT(ISODOW FROM candidate)::int; -- 1..7 (Mon..Sun)
    -- match dow
    IF dows = '*' OR
       (dows = '1-5' AND dow_int BETWEEN 1 AND 5) OR
       (dows ~ '^\d+$' AND dow_int = dows::int)
    THEN
      FOREACH h IN ARRAY hours LOOP
        FOREACH m IN ARRAY mins LOOP
          candidate := date_trunc('day', (base + make_interval(days => d)))
                       + make_interval(hours => h, mins => m);
          IF candidate > base AND (best IS NULL OR candidate < best) THEN
            best := candidate;
          END IF;
        END LOOP;
      END LOOP;
    END IF;
    EXIT WHEN best IS NOT NULL;
  END LOOP;

  UPDATE public.ai_agents SET next_run_at = best WHERE id = p_agent_id;
  RETURN best;
END;
$$;

REVOKE ALL ON FUNCTION public.ai_recompute_next_run(uuid) FROM public;
GRANT EXECUTE ON FUNCTION public.ai_recompute_next_run(uuid) TO authenticated;